### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by nastarfan** [react-native-community/docker-android#139]
Hi, I am trying to run CICD on gitlab for my react native project using this docker image, using this setup:
```
build:
  image: reactnativecommunity/react-native-android:latest
  stage: build
  script:
    - npm install
    - cd android && chmod +x gradlew
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - android/app/build/outputs/
```

But it always fail with this error:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! Maximum call stack size exceeded
```

Since I am not quite familiar with docker, if anyone has direction on how to resolve this issue, that would be much appreciated. From my understanding, the npm version of the image is not up to date with the one my team uses, but I don't know how to properly match the npm version from the image
